### ISSUE TITLE
when CL create report, error show up (image) but the report is still created

### ISSUE THREAD

**Issue by viochan2304** [smonv/cmr_comp1640#22]
![3-22-2016 9-24-15 pm](https://cloud.githubusercontent.com/assets/16721492/13955003/a1a6a31c-f075-11e5-9b19-4abb66348331.png)

**Comment by smonv** [comment]
kiểm tra lại cái mail xem, null này hay do nó

**Comment by viochan2304** [comment]
sửa mail rồi, nhận đc mail khi đc admin assign vào course mà

**Comment by smonv** [comment]
được rồi t sẽ debug lại đoạn đó. Sendmail là async nên khi bị null nó sẽ lại nhảy xuống dòng transaction. dkw :anger:
