### ISSUE TITLE
[Admin-Course]

### ISSUE THREAD

**Issue by rysergt** [smonv/cmr_comp1640#26]
-Login admin1
-List Courses
-Edit Course
-Leave all field blank
-Click Save
---> rip

**Comment by rysergt** [comment]
http://imgur.com/a/ipVyH

**Comment by smonv** [comment]
image pls

**Comment by smonv** [comment]
github có up ảnh, đừng có dùng imgur

**Comment by smonv** [comment]
fixed in 192c02bbded10f80198c27493b199a58c6fbd72d
