### ISSUE TITLE
[CL-Create Report-Edit Report]

### ISSUE THREAD

**Issue by rysergt** [smonv/cmr_comp1640#27]
CL create / edit report
Leave all fields (or any random field) blank
Click create / edit
--> rip

**Comment by rysergt** [comment]
-CL ko can comment 
-CL ko can delete
-Mot khi report da duoc approved thi CL ko vao xem duoc nua 
--> "This report is approved! You can't access it anymore!"

**Comment by viochan2304** [comment]
CL vẫn đc xem report approved của mình chứ

**Comment by rysergt** [comment]
"The CL and CM can only access their own CMRs until they are approved"

**Comment by smonv** [comment]
Rip create / edit report fixed in 43967fe1c20e7bd7072d92f5756cf61a43e4a4f5
Vụ comment và delete move qua issue khác.
