### ISSUE TITLE
[CM - Unapprove Report]

### ISSUE THREAD

**Issue by rysergt** [smonv/cmr_comp1640#28]
- Hien tai neu CM muon unapprove report thi phai approve roi moi duoc unapprove.
  -->Them nut Unapprove vao de CM co the unapprove report truc tiep luon.
- CM ko can nut delete
- Mot khi report da duoc approved thi CM ko vao xem duoc nua 
  --> "This report is approved! You can't access it anymore!"
- CM ko can comment (or chi can neu co y dinh lam them chuc nang comment khi unapprove de CL doc duoc comment cua CM) (trong de ko yeu cau)

**Comment by smonv** [comment]
cái unapprove không cần thiết vì lúc nào nó cũng là unapprove rồi. Unapprove ở đây chỉ nhằm mục đích unlock cho CL nó edit

**Comment by viochan2304** [comment]
CL vs CM vẫn đc xem report đã approve, chỉ là ko đc sửa chữa với xóa hay tạo cái mới thôi

**Comment by rysergt** [comment]
"The CL and CM can only access their own CMRs until they are approved"
Một khi đã edit là ko làm gì đc nữa cả, vì nó dùng để gửi đi cho DLT PVC xem rồi

**Comment by smonv** [comment]
thì sau khi CM đã approve, CL sẽ không access được trang report edit nữa, cái đó đã làm rồi.
Comment là thứ riêng biệt, cả CL, CM và DLT đều thấy và send comment được kể cả sau khi approve vì DLT chỉ access được và comment được vào approved report
