### ISSUE TITLE
Can admin delete courses & faculties ?

### ISSUE THREAD

**Issue by rysergt** [smonv/cmr_comp1640#38]
- Admin > Faculty Detail > Doesn't have delete button
- Admin > Course Detail > Has delete button but doesn't work

![capture](https://cloud.githubusercontent.com/assets/7535963/14116480/2841d330-f60a-11e5-81a5-58d6d3f30448.PNG)

**Comment by smonv** [comment]
Sẽ k có delete gì cả. Những chỗ nào còn delete button sẽ vứt đi sau
